### ISSUE TITLE
Overlay doesn't close on touch

### ISSUE THREAD

**Issue by mspanish** [gao-sun/windowise#2]
I'm on a Dell touch enabled laptop using Chrome Version 59.0.3071.115 (Official Build) (64-bit)

When I click the overlay it works fine, but touching the overlay with my finger does not close it.

**Comment by gao-sun** [comment]
Thank you for your issue! I'm on a trip and will fix it ASAP when I come back.

**Comment by gao-sun** [comment]
It has only 2 days left :-)

**Comment by mspanish** [comment]
I commented out the e.preventDefault() and that seemed to fix the problem - although I'm sure it creates others as this is meant to make the listener passive, right?
```
this.overlay.addEventListener("touchstart",function(e){
//	e.preventDefault()
}
```

**Comment by gao-sun** [comment]
Yes, I added this listener to prevent scrolling on the phone when overlay shows. Now it's fixed. Thank you for the issue and your patience!

**Comment by mspanish** [comment]
great thanks for this LOVELY library, my project will be live in a few days and I'll send you the URL so you can get a look - your system powers all of my notifications and modals, of which there are many!

**Comment by gao-sun** [comment]
Awesome! I look forward to seeing your project and I'm so happy that my library could help you. Please let me know if there is anything I can help in the future.

**Comment by mspanish** [comment]
🥇
